version: '3.8'

services:
  postgres:
    container_name: appFreelancer
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rafael7531
      - POSTGRES_DB=app_Freelancer